[Service]
UMask=0077
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
NoNewPrivileges=true
RestrictSUIDSGID=true
LockPersonality=true
SystemCallArchitectures=native
CapabilityBoundingSet=
AmbientCapabilities=
